workflows:
  ios-workflow:
    name: iOS Build Fast & Future-Proof
    max_build_duration: 60

    environment:
      ruby: 3.4.7

    scripts:
      # ===============================
      # 0️⃣ Fast wipe only for safety (not full VM)
      # ===============================
      - name: CLEAN LOCAL BUILD ARTIFACTS
        script: |
          echo "===== CLEAN LOCAL BUILD ARTIFACTS ====="
          rm -rf build
          rm -rf ios/DerivedData || true
          rm -rf ios/.symlinks || true

      # ===============================
      # 1️⃣ Flutter
      # ===============================
      - name: Install Flutter 3.36.3
        script: |
          git clone -b 3.36.3 https://github.com/flutter/flutter.git ~/flutter
          export PATH="$PATH:~/flutter/bin"
          flutter --version

      - name: Flutter clean
        script: flutter clean

      - name: Flutter pub get
        script: flutter pub get

      # ===============================
      # 2️⃣ Pod install (cache-friendly)
      # ===============================
      - name: Install Pods
        script: |
          cd ios
          pod install --repo-update
          cd ..

      # ===============================
      # 3️⃣ Strip -G from all xcconfig (future-proof)
      # ===============================
      - name: STRIP -G FROM ALL XCCONFIG
        script: |
          echo "===== STRIPPING -G FLAG FROM XCCONFIG ====="
          find ios -name "*.xcconfig" -exec sed -i 's/ -G//g' {} \;
          find ios -name "*.xcconfig" -exec sed -i 's/-G //g' {} \;
          find ios -name "*.xcconfig" -exec sed -i 's/-G//g' {} \;

      # ===============================
      # 4️⃣ Patch BoringSSL / gRPC per-file COMPILER_FLAGS (future-proof)
      # ===============================
      - name: PATCH BORINGSSL / GRPC COMPILER_FLAGS
        script: |
          echo "===== PATCHING ALL -GCC WARNINGS IN Pods.xcodeproj ====="
          PBX=ios/Pods/Pods.xcodeproj/project.pbxproj
          sed -i 's/-GCC_WARN_INHIBIT_ALL_WARNINGS//g' $PBX
          sed -i 's/-G//g' $PBX
          sed -i 's/  / /g' $PBX
          echo "===== VERIFY PATCH ====="
          grep -R "GCC_WARN_INHIBIT" ios/Pods || echo "✅ ALL FLAGS REMOVED"

      # ===============================
      # 5️⃣ Build iOS Release (no codesign)
      # ===============================
      - name: Build iOS Release
        script: flutter build ios --release --no-codesign
