workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install Bundler & Gems
        script: |
          gem install bundler -v 2.7.2
          bundle _2.7.2_ install
      - name: Flutter pub get
        script: |
          flutter pub get
      - name: Pod install
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          bundle exec pod install --repo-update
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
