workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 120

    environment:
      flutter: stable
      ruby: 3.4.6
      xcode: latest
      vars:
        FLUTTER_BUILD_MODE: release

    scripts:
      # 1️⃣ Bersihkan project
      - name: Clean Flutter project
        script: flutter clean

      # 2️⃣ Get dependencies Flutter
      - name: Get Flutter dependencies
        script: flutter pub get

      # 3️⃣ Install CocoaPods
      - name: Install CocoaPods
        script: |
          export PATH="$HOME/.rbenv/shims:$PATH"
          gem install cocoapods -v 1.16.2
          pod setup

      # 4️⃣ Generate Flutter iOS artifacts
      - name: Generate iOS Flutter artifacts
        script: |
          flutter precache --ios
          cd ios
          pod repo update
          pod install
          cd ..

      # 5️⃣ Build iOS for simulator first (important!)
      - name: Build iOS simulator
        script: flutter build ios --simulator

      # 6️⃣ Build iOS release (device, no codesign)
      - name: Build iOS release
        script: flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/iphoneos/*.ipa
