workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      xcode: latest
      ruby: 3.4.7
      flutter: 3.36.3  # versi kompatibel Xcode 15+

    scripts:
      - name: Disable rbenv & install CocoaPods
        script: |
          export RBENV_VERSION=
          export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
          brew update
          brew install cocoapods
          pod --version

      - name: Flutter clean
        script: flutter clean

      - name: Remove iOS build artifacts
        script: rm -rf ios/Pods ios/Podfile.lock ~/Library/Developer/Xcode/DerivedData

      - name: Flutter pub get
        script: flutter pub get

      - name: Pod install
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build iOS (Release, no codesign)
        script: flutter build ios --release --no-codesign
