scripts:
  - name: Clean Flutter project
    script: |
      flutter clean
      rm -rf ios/Pods ios/Podfile.lock ios/.symlinks ios/Flutter

  - name: Get Flutter dependencies
    script: flutter pub get

  - name: Generate Flutter iOS artifacts
    script: flutter precache --ios

  - name: Setup CocoaPods
    script: gem install cocoapods -v 1.16.2

  - name: Install iOS Pods
    script: |
      cd ios
      pod repo update
      pod install
      cd ..

  - name: Build iOS Release
    script: flutter build ios --release --no-codesign
