workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60

    environment:
      xcode: 15.2
      ruby: 3.4.7

    scripts:
      - name: Install Flutter 3.36.3
        script: |
          git clone -b 3.36.3 https://github.com/flutter/flutter.git ~/flutter
          export PATH="$PATH:~/flutter/bin"
          flutter --version

      - name: Flutter clean
        script: flutter clean

      - name: Remove old iOS artifacts
        script: |
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock
          rm -rf ~/Library/Developer/Xcode/DerivedData

      - name: Flutter pub get
        script: flutter pub get

      - name: Force clean iOS pods
        script: |
          cd ios
          pod deintegrate
          pod install --repo-update
          cd ..

      - name: Build iOS (Release, no codesign)
        script: flutter build ios --release --no-codesign
