workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      xcode: latest
      ruby: 3.4.7   # cocok dengan rbenv di Codemagic

    scripts:
      - name: Disable rbenv & install CocoaPods
        script: |
          # Matikan rbenv supaya tidak override pod
          export RBENV_VERSION=
          export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"

          brew update
          brew install cocoapods

          which pod
          pod --version

      - name: Flutter clean (WAJIB)
        script: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock

      - name: Flutter pub get
        script: flutter pub get

      - name: Pod install
        script: |
          export RBENV_VERSION=
          export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
          cd ios
          pod install --repo-update
          cd ..

      - name: Build iOS (Release, no codesign)
        script: |
          # ⚡ Build iOS tanpa codesign dan override flags -G
          flutter build ios --release --no-codesign -- \
            OTHER_CFLAGS="" OTHER_LDFLAGS=""
