workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 90

    environment:
      flutter: stable
      xcode: latest
      ruby: 3.4.6

    scripts:
      - name: Flutter clean
        script: flutter clean

      - name: Get Flutter packages
        script: flutter pub get

      - name: Install CocoaPods
        script: |
          export PATH="$HOME/.rbenv/shims:$PATH"
          gem install cocoapods -v 1.16.2
          pod setup

      - name: Install iOS pods
        script: |
          flutter precache --ios
          cd ios
          pod deintegrate
          pod install --repo-update
          cd ..

      - name: Build iOS release
        script: flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/*.app
