workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      xcode: latest
    scripts:
     - name: Install Bundler & Gems
  script: |
    gem install bundler:2.7.2
    bundle _2.7.2_ install

      - name: Pod install (via Bundler)
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          bundle exec pod install --repo-update

      - name: Build iOS
        script: |
          flutter pub get
          flutter build ios --release --no-codesign
