workflows:
  ios-release:
    name: iOS Release Build
    environment:
      flutter: 3.12.3          # versi Flutter tersedia di runner
      xcode: latest            # gunakan Xcode 14+ untuk Firebase 6.x
      ruby: 3.4.6
      vars:
        FLUTTER_BUILD_MODE: release

    scripts:
      - name: Clean Flutter project
        script: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock

      - name: Get Flutter dependencies
        script: flutter pub get

      - name: Setup CocoaPods
        script: |
          # Pastikan Ruby sesuai
          rbenv install -s 3.4.6
          rbenv global 3.4.6
          ruby -v

          # Install CocoaPods versi kompatibel
          gem install cocoapods -v 1.16.2
          pod --version

      - name: Install iOS Pods
        script: |
          cd ios
          pod repo update         # pastikan repo pods terbaru
          pod install             # install plugin termasuk cloud_firestore
          cd ..

      - name: Build iOS Release
        script: |
          flutter clean           # optional, memastikan build fresh
          flutter pub get         # pastikan semua dependency terambil
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/iphoneos/*.ipa
