workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 90
    environment:
      xcode: latest
      ruby: 3.4.7  # supaya cocok dengan rbenv di Codemagic
      cocoapods: 1.16.2  # gunakan versi stabil

    scripts:
      # 1️⃣ Install Flutter 3.35.7
      - name: Install Flutter
        script: |
          echo "Installing Flutter 3.35.7..."
          git clone -b 3.35.7 https://github.com/flutter/flutter.git ~/flutter
          export PATH="$PATH:~/flutter/bin"
          flutter --version

      # 2️⃣ Disable rbenv & install CocoaPods
      - name: Disable rbenv & install CocoaPods
        script: |
          export RBENV_VERSION=
          export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
          brew update
          brew install cocoapods
          pod --version

      # 3️⃣ Flutter clean
      - name: Flutter clean
        script: flutter clean

      # 4️⃣ Remove iOS artifacts
      - name: Remove old iOS build artifacts
        script: |
          rm -rf ios/Pods ios/Podfile.lock ~/Library/Developer/Xcode/DerivedData

      # 5️⃣ Get Flutter dependencies
      - name: Flutter pub get
        script: flutter pub get

      # 6️⃣ Pod install
      - name: Pod install
        script: |
          cd ios
          pod install --repo-update
          cd ..

      # 7️⃣ Build iOS simulator
      - name: Build iOS Simulator
        script: flutter build ios --simulator

      # 8️⃣ Build iOS device (release, no codesign)
      - name: Build iOS (Release, no codesign)
        script: flutter build ios --release --no-codesign
