workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      xcode: latest
      ruby: 3.4.7

    scripts:
      - name: Install Flutter 3.35.7
        script: |
          git clone -b 3.35.7 https://github.com/flutter/flutter.git ~/flutter
          export PATH="$PATH:~/flutter/bin"
          flutter --version

      - name: Install CocoaPods
        script: |
          export RBENV_VERSION=
          export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
          brew update
          brew install cocoapods
          pod --version

      - name: Flutter clean
        script: flutter clean

      - name: Remove old iOS build artifacts
        script: rm -rf ios/Pods ios/Podfile.lock ~/Library/Developer/Xcode/DerivedData

      - name: Flutter pub get
        script: flutter pub get

      - name: Pod install
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Patch Pods to remove -G
        script: |
          ruby -e "
          require 'xcodeproj';
          installer_path = 'ios/Pods/Pods.xcodeproj';
          project = Xcodeproj::Project.open(installer_path);

          project.targets.each do |target|
            target.build_configurations.each do |config|
              ['OTHER_CFLAGS','OTHER_LDFLAGS'].each do |key|
                if config.build_settings[key]
                  value = config.build_settings[key]
                  if value.is_a?(Array)
                    config.build_settings[key] = value.reject { |f| f == '-G' }
                  elsif value.is_a?(String)
                    config.build_settings[key] = value.split.reject { |f| f == '-G' }.join(' ')
                  end
                end
              end
            end
          end

          project.save;
          "

      - name: Build iOS (Release, no codesign)
        script: flutter build ios --release --no-codesign
