workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      xcode: latest
      ruby: 3.4.7

    scripts:
      - name: Install Flutter 3.36.3
        script: |
          git clone -b 3.36.3 https://github.com/flutter/flutter.git ~/flutter
          export PATH="$PATH:~/flutter/bin"
          flutter --version

      - name: Flutter clean
        script: flutter clean

      - name: Remove old iOS artifacts
        script: rm -rf ios/Pods ios/Podfile.lock ~/Library/Developer/Xcode/DerivedData

      - name: Flutter pub get
        script: flutter pub get

      - name: Pod install
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build iOS (Release, no codesign)
        script: flutter build ios --release --no-codesign
