workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      xcode: latest
    scripts:
      - name: Force Ruby 3.2.2
        script: |
          rbenv install 3.2.2 || true
          rbenv global 3.2.2
          ruby -v

      - name: Install CocoaPods
        script: |
          gem install cocoapods -v 1.13.0
          pod --version

      - name: Pod install
        script: |
          cd ios
          pod install

      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
