workflows:
  ios-release:
    name: iOS Release Build
    environment:
      flutter: 3.35.7
      xcode: latest
      cocoapods: 1.16.2
      ruby: 3.4.7

    scripts:
      - name: Clean Flutter
        script: flutter clean
      - name: Get dependencies
        script: flutter pub get
      - name: Install pods
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod repo update
          pod install
          cd ..
      - name: Build iOS Release
        script: flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/iphoneos/*.ipa
