workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      xcode: latest
      ruby: 3.4.7

    scripts:
      # 1️⃣ Install Flutter 3.35.7
      - name: Install Flutter 3.35.7
        script: |
          echo "Installing Flutter 3.35.7..."
          git clone -b 3.35.7 https://github.com/flutter/flutter.git ~/flutter
          export PATH="$PATH:~/flutter/bin"
          flutter --version

      # 2️⃣ Disable rbenv & install CocoaPods
      - name: Disable rbenv & install CocoaPods
        script: |
          export RBENV_VERSION=
          export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
          brew update
          brew install cocoapods
          pod --version

      # 3️⃣ Clean Flutter & iOS build artifacts
      - name: Flutter clean + remove iOS artifacts
        script: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock ~/Library/Developer/Xcode/DerivedData

      # 4️⃣ Get Flutter dependencies
      - name: Flutter pub get
        script: flutter pub get

      # 5️⃣ Install pods
      - name: Pod install
        script: |
          cd ios
          pod install --repo-update
          cd ..

      # 6️⃣ Build iOS simulator (no codesign)
      - name: Build iOS Simulator
        script: flutter build ios --simulator --no-codesign

      # 7️⃣ Build iOS device (no codesign)
      - name: Build iOS Device
        script: flutter build ios --release --no-codesign
