workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      os: macOS
    scripts:
      - name: Clean project
        script: |
          flutter clean
          rm -rf ios/Pods ios/Runner.xcworkspace ios/Flutter/Flutter.podspec

      - name: Get Flutter dependencies
        script: flutter pub get

      - name: Generate iOS artifacts
        script: flutter precache --ios

      - name: Install CocoaPods
        script: |
          gem install cocoapods -v 1.16.2
          pod repo update
          cd ios
          pod install
          cd ..

      - name: Build iOS release (no codesign)
        script: flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/Runner.app
