workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      xcode: latest
      ruby: 3.4.7   # ⬅️ PENTING: samakan dengan rbenv yang ada

    scripts:
      - name: Disable rbenv & install CocoaPods
        script: |
          # Matikan rbenv supaya tidak override pod
          export RBENV_VERSION=
          export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"

          brew update
          brew install cocoapods

          which pod
          pod --version

      - name: Flutter pub get
        script: flutter pub get

      - name: Clean iOS build artifacts
        script: |
          cd ios
          rm -rf Pods Podfile.lock ~/Library/Developer/Xcode/DerivedData
          cd ..

      - name: Pod install
        script: |
          export RBENV_VERSION=
          export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
          cd ios
          pod install --repo-update
          cd ..

      - name: Build iOS (Release, no codesign)
        script: flutter build ios --release --no-codesign
