workflows:
  ios-release:
    name: iOS Release Build
    environment:
      flutter: 3.35.7         # Versi Flutter proyekmu
      xcode: latest           # Gunakan Xcode terbaru (14+)
      ruby: 3.4.6
      vars:
        FLUTTER_BUILD_MODE: release

    scripts:
      - name: Clean Flutter project
        script: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock ios/.symlinks ios/Flutter/Flutter.framework ios/Flutter/Flutter.podspec

      - name: Get Flutter dependencies
        script: flutter pub get

      - name: Setup CocoaPods
        script: |
          rbenv install -s 3.4.6
          rbenv global 3.4.6
          ruby -v
          gem install cocoapods -v 1.16.2
          pod --version

      - name: Install iOS Pods
        script: |
          cd ios
          pod repo update
          pod install --repo-update
          cd ..

      - name: Build iOS Release
        script: flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/iphoneos/*.ipa
