workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      ruby: 3.2.2
      xcode: latest

    scripts:
      - name: Install Homebrew CocoaPods
        script: |
          brew update
          brew install cocoapods
          pod --version

      - name: Flutter pub get
        script: flutter pub get

      - name: Clean iOS build artifacts
        script: |
          cd ios
          rm -rf Pods Podfile.lock ~/Library/Developer/Xcode/DerivedData
          cd ..

      - name: Pod install
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build iOS (Release, no codesign)
        script: flutter build ios --release --no-codesign
