workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      xcode: latest
      ruby: 3.4.7
      # Flutter akan diinstall manual, jadi versi di environment bisa dibiarkan kosong
      flutter: ""

    scripts:
      # 1️⃣ Install Flutter 3.36.3 manually
      - name: Install Flutter 3.36.3
        script: |
          echo "Installing Flutter 3.36.3..."
          git clone -b 3.36.3 https://github.com/flutter/flutter.git ~/flutter
          export PATH="$PATH:~/flutter/bin"
          flutter --version

      # 2️⃣ Disable rbenv & install CocoaPods
      - name: Disable rbenv & install CocoaPods
        script: |
          export RBENV_VERSION=
          export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
          brew update
          brew install cocoapods
          pod --version

      # 3️⃣ Flutter clean
      - name: Flutter clean
        script: flutter clean

      # 4️⃣ Remove old iOS artifacts
      - name: Remove iOS build artifacts
        script: |
          rm -rf ios/Pods ios/Podfile.lock ~/Library/Developer/Xcode/DerivedData

      # 5️⃣ Get Flutter dependencies
      - name: Flutter pub get
        script: flutter pub get

      # 6️⃣ Install pods
      - name: Pod install
        script: |
          cd ios
          pod install --repo-update
          cd ..

      # 7️⃣ Build iOS for device (release, no codesign)
      - name: Build iOS (Release, no codesign)
        script: flutter build ios --release --no-codesign
