workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      xcode: latest
    scripts:
      - name: Install CocoaPods
        script: |
          gem install cocoapods -v 1.13.0

      - name: Fix ActiveSupport (CRITICAL)
        script: |
          gem uninstall activesupport -aIx || true
          gem install activesupport -v 7.0.8

      - name: Pod install
        script: |
          cd ios
          pod install --repo-update

      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
