workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60

    environment:
      ruby: 3.4.7

    scripts:
      - name: Install Flutter 3.36.3
        script: |
          git clone -b 3.36.3 https://github.com/flutter/flutter.git ~/flutter
          export PATH="$PATH:~/flutter/bin"
          flutter --version

      - name: Flutter clean
        script: |
          flutter clean

      - name: Remove old iOS artifacts
        script: |
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock
          rm -rf ~/Library/Developer/Xcode/DerivedData

      - name: Flutter pub get
        script: |
          flutter pub get

      - name: Reinstall Pods
        script: |
          cd ios
          pod deintegrate || true
          pod install --repo-update
          cd ..

      # 🔥 INI SENJATA UTAMA
      - name: FORCE REMOVE -G FLAG (KILLER STEP)
        script: |
          echo "===== STRIPPING -G FLAG FROM ALL XCCONFIG ====="
          find ios -name "*.xcconfig" -print
          find ios -name "*.xcconfig" -exec sed -i 's/ -G//g' {} \;
          find ios -name "*.xcconfig" -exec sed -i 's/-G //g' {} \;
          find ios -name "*.xcconfig" -exec sed -i 's/-G//g' {} \;

      - name: Debug - ensure no -G remains
        script: |
          echo "===== VERIFY ====="
          grep -R " -G" ios || echo "OK: no -G flag found"

      - name: Build iOS (Release, no codesign)
        script: |
          flutter build ios --release --no-codesign
