workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 60
    environment:
      flutter: 3.35.7 # ganti sesuai versi project
      xcode: 15.3
      cocoapods: 1.16.2
      ruby: 3.4.7
      vars:
        PROJECT_DIR: $CM_BUILD_DIR

    scripts:
      # 1. Bersihkan cache Flutter
      - name: Flutter clean
        script: flutter clean

      # 2. Hapus Pods lama & DerivedData
      - name: Remove old iOS artifacts
        script: |
          rm -rf ios/Pods ios/Podfile.lock
          rm -rf ~/Library/Developer/Xcode/DerivedData

      # 3. Ambil dependencies Flutter
      - name: Flutter pub get
        script: flutter pub get

      # 4. Install pods + patch -G flag
      - name: Pod install with patch
        script: |
          cd ios
          pod install --repo-update
          # Hapus flag -G di semua build file
          ruby -pi -e 'gsub(/\s?-G\s?/, " ")' Pods/Pods.xcodeproj/project.pbxproj
          cd ..

      # 5. Build iOS release tanpa codesign
      - name: Build iOS Release
        script: flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/iphoneos/*.ipa
