workflows:
  ios-release-no-codesign:
    name: Build iOS Release (no codesign)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        FLUTTER_BUILD_MODE: release
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Build iOS release without codesign
        script: |
          flutter clean
          flutter build ios --release --no-codesign
      - name: Create IPA manually
        script: |
          # Buat folder payload
          mkdir -p build/ios/iphoneos/Payload
          cp -r build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload/
          # Zip menjadi IPA
          cd build/ios/iphoneos
          zip -r Runner.ipa Payload
          cd ../../../..
    artifacts:
      - build/ios/iphoneos/Runner.app
      - build/ios/iphoneos/Runner.ipa
