workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      xcode: latest
    scripts:
      - name: Clean CocoaPods
        script: |
          gem uninstall cocoapods -aIx || true

      - name: Install CocoaPods 1.12.1 (STABLE)
        script: |
          gem install cocoapods -v 1.12.1
          pod --version

      - name: Pod install
        script: |
          cd ios
          pod install --repo-update

      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
