workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 90

    environment:
      flutter: stable
      ruby: 3.4.6
      vars:
        FLUTTER_BUILD_MODE: release

    scripts:
      - name: Clean Flutter project
        script: flutter clean

      - name: Get Flutter dependencies
        script: flutter pub get

      - name: Install CocoaPods
        script: |
          export PATH="$HOME/.rbenv/shims:$PATH"
          gem install cocoapods -v 1.16.2
          pod setup

      - name: Generate iOS Flutter artifacts
        script: |
          flutter precache --ios
          flutter pub get
          cd ios
          pod repo update
          pod install
          cd ..

      - name: Build iOS release
        script: flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/iphoneos/*.ipa
