workflows:
  ios-workflow:
    name: iOS Build (Hard Reset + Patch BoringSSL)
    max_build_duration: 60

    environment:
      ruby: 3.4.7

    scripts:
      # ======================================
      # 🔥 FORCE WIPE ALL CACHE (WAJIB)
      # ======================================
      - name: FORCE WIPE ALL CACHE
        script: |
          echo "===== FORCE WIPE CODEMAGIC VM ====="
          rm -rf ~/.cocoapods
          rm -rf ~/Library/Caches/CocoaPods
          rm -rf ~/Library/Developer/Xcode/DerivedData
          rm -rf ~/.pub-cache
          rm -rf ~/.dartServer
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock
          rm -rf ios/.symlinks
          rm -rf build

      # ======================================
      # 🔍 VERIFY CLEAN STATE
      # ======================================
      - name: Verify clean state
        script: |
          echo "===== VERIFY CLEAN ====="
          ls ios/Pods && echo "❌ Pods still exist" || echo "✅ Pods clean"
          ls build && echo "❌ build dir exists" || echo "✅ build clean"

      # ======================================
      # FLUTTER
      # ======================================
      - name: Install Flutter 3.36.3
        script: |
          git clone -b 3.36.3 https://github.com/flutter/flutter.git ~/flutter
          export PATH="$PATH:~/flutter/bin"
          flutter --version

      - name: Flutter clean
        script: flutter clean

      - name: Flutter pub get
        script: flutter pub get

      # ======================================
      # COCOAPODS
      # ======================================
      - name: Reinstall Pods
        script: |
          cd ios
          pod deintegrate || true
          pod install --repo-update
          cd ..

      # ======================================
      # 🧨 STRIP -G FLAG (xcconfig) – cadangan
      # ======================================
      - name: FORCE REMOVE -G FROM ALL XCCONFIG
        script: |
          echo "===== STRIPPING -G FLAG FROM XCCONFIG ====="
          find ios -name "*.xcconfig" -print
          find ios -name "*.xcconfig" -exec sed -i 's/ -G//g' {} \;
          find ios -name "*.xcconfig" -exec sed -i 's/-G //g' {} \;
          find ios -name "*.xcconfig" -exec sed -i 's/-G//g' {} \;

      - name: Verify no -G remains
        script: |
          echo "===== VERIFY -G ====="
          grep -R " -G" ios || echo "✅ NO -G FOUND"

      # ======================================
      # 🧨 PATCH BORINGSSL / GRPC PER-FILE FLAG
      # ======================================
      - name: PATCH BORINGSSL -GCC FLAG
        script: |
          echo "===== PATCHING BoringSSL / gRPC FLAGS ====="
          PBX=ios/Pods/Pods.xcodeproj/project.pbxproj

          sed -i 's/-GCC_WARN_INHIBIT_ALL_WARNINGS//g' $PBX
          sed -i 's/  / /g' $PBX

          echo "===== VERIFY ====="
          grep -R "GCC_WARN_INHIBIT" ios/Pods || echo "✅ FLAG REMOVED"

      # ======================================
      # BUILD IOS RELEASE
      # ======================================
      - name: Build iOS (Release, no codesign)
        script: flutter build ios --release --no-codesign
