workflows:
  ios-release-simple:
    name: Build iOS Release (with codesign)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        FLUTTER_BUILD_MODE: release
        APPLE_ID: "antarakita208@gmail.com" # Ganti dengan Apple ID kamu
        APP_SPECIFIC_PASSWORD: "Asdf4455"  # Gunakan secret variable di Codemagic jika repo public
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Build iOS release with codesign
        script: |
          flutter clean
          flutter build ios --release
      - name: Export IPA
        script: |
          xcodebuild -exportArchive -archivePath build/ios/archive/Runner.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath build/ios/iphoneos
      - name: Upload to App Store Connect
        script: |
          xcrun altool --upload-app -f build/ios/iphoneos/Runner.ipa -t ios -u $APPLE_ID -p $APP_SPECIFIC_PASSWORD --verbose
    artifacts:
      - build/ios/iphoneos/Runner.app
      - build/ios/iphoneos/Runner.ipa
