workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      ruby: 3.2.2
    scripts:
      - name: Flutter pub get
        script: |
          flutter pub get

      - name: Install CocoaPods
        script: |
          sudo gem install cocoapods -v 1.13.0

      - name: Pod install
        script: |
          cd ios
          pod install

      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
