workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      xcode: latest
      ruby: 3.2.2  # pastikan versi Ruby cocok untuk Cocoapods 1.12.1
    scripts:
      - name: Install Bundler
        script: |
          gem install bundler
          bundle install

      - name: Pod install (via Bundler)
        script: |
          cd ios
          bundle exec pod install --repo-update

      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
