workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      ruby: 3.2.2
      xcode: latest

    scripts:
      - name: Install Bundler & Gems
        script: |
          gem install bundler -v 2.7.2
          bundle install
          # Hapus CocoaPods sistem jika ada
          sudo gem uninstall cocoapods -a || true
          sudo gem cleanup || true

      - name: Flutter pub get
        script: flutter pub get

      - name: Clean iOS build artifacts
        script: |
          cd ios
          rm -rf Pods Podfile.lock ~/Library/Developer/Xcode/DerivedData
          cd ..

      - name: Pod install (via Bundler)
        script: |
          cd ios
          bundle exec pod install --repo-update
          cd ..

      - name: Build iOS (Release, no codesign)
        script: flutter build ios --release --no-codesign
