workflows:
  ios-release:
    name: iOS Release Build
    environment:
      flutter: 3.12.3       # gunakan versi Flutter bawaan runner
      xcode: latest         # Xcode 14+ untuk Firebase 6.x
      # ruby tidak perlu di-set, pakai Ruby bawaan runner

    scripts:
      - name: Clean Flutter project
        script: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock

      - name: Get Flutter dependencies
        script: flutter pub get

      - name: Install CocoaPods
        script: |
          sudo gem install cocoapods -v 1.16.2 || true
          pod --version

      - name: Install iOS Pods
        script: |
          cd ios
          pod repo update
          pod install
          cd ..

      - name: Build iOS Release
        script: flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/iphoneos/*.ipa
