workflows:
  ios-release-simple:
    name: Build iOS Release (no codesign)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      # Tidak perlu Apple ID / provisioning profile
      vars:
        FLUTTER_BUILD_MODE: release
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Build iOS release
        script: |
          flutter clean
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
      - build/ios/iphoneos/Runner.ipa
