// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZdSGOGMQ7AglU3OvNGPz39C8dfQNwtME',
    appId: '1:664030112148:web:099baef3acc46b633b0781',
    messagingSenderId: '664030112148',
    projectId: 'projectgm-c1b05',
    authDomain: 'projectgm-c1b05.firebaseapp.com',
    storageBucket: 'projectgm-c1b05.firebasestorage.app',
    measurementId: 'G-9LC8YDECK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCivdtlgsbF5tzMFBLQLT1p_F0jvXbw9kg',
    appId: '1:664030112148:android:1141e355199f2b643b0781',
    messagingSenderId: '664030112148',
    projectId: 'projectgm-c1b05',
    storageBucket: 'projectgm-c1b05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBve0EdfQm1WRQOzvztpn5t-XQL5F8mc1Q',
    appId: '1:664030112148:ios:cccf28504c0a3dae3b0781',
    messagingSenderId: '664030112148',
    projectId: 'projectgm-c1b05',
    storageBucket: 'projectgm-c1b05.firebasestorage.app',
    iosBundleId: 'com.example.tap1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBve0EdfQm1WRQOzvztpn5t-XQL5F8mc1Q',
    appId: '1:664030112148:ios:cccf28504c0a3dae3b0781',
    messagingSenderId: '664030112148',
    projectId: 'projectgm-c1b05',
    storageBucket: 'projectgm-c1b05.firebasestorage.app',
    iosBundleId: 'com.example.tap1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZdSGOGMQ7AglU3OvNGPz39C8dfQNwtME',
    appId: '1:664030112148:web:464a5314667073213b0781',
    messagingSenderId: '664030112148',
    projectId: 'projectgm-c1b05',
    authDomain: 'projectgm-c1b05.firebaseapp.com',
    storageBucket: 'projectgm-c1b05.firebasestorage.app',
    measurementId: 'G-PPT9WD6BR1',
  );
}
