# ios/Podfile

platform :ios, '14.0'

# Disable CocoaPods analytics
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# Ignore warnings
inhibit_all_warnings!

use_frameworks!
use_modular_headers!

target 'Runner' do
  # Pods for Runner
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__)) rescue nil

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
        %w[OTHER_CFLAGS OTHER_LDFLAGS].each do |key|
          next unless config.build_settings[key]
          config.build_settings[key] = config.build_settings[key].split.reject { |f| f == '-G' }.join(' ')
        end
      end
    end
  end
end
